"""
Scene Schema — data model for representing Isaac Sim scenes.

A SceneConfig is a complete, structured representation of an Isaac Sim
scene that can be:
  1. Generated by an LLM from a natural language description
  2. Built in Isaac Sim via the MCP client
  3. Stored and retrieved from the scene registry
  4. Varied automatically for domain randomization

Scene configs are fully serializable to/from JSON/YAML.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Any, Dict, List, Optional, Tuple


class ObjectShape(Enum):
    CUBE = "Cube"
    SPHERE = "Sphere"
    CYLINDER = "Cylinder"
    CAPSULE = "Capsule"
    CONE = "Cone"
    MESH = "Mesh"
    PLANE = "Plane"
    TORUS = "Torus"
    DISC = "Disc"


class RobotModel(Enum):
    FRANKA = "franka"
    UR5 = "ur5"
    UR10 = "ur10"


class TaskCategory(Enum):
    REACH = "reach"
    GRASP = "grasp"
    PICK_PLACE = "pick_place"
    INSERTION = "insertion"
    PUSH = "push"
    PULL = "pull"
    STACK = "stack"
    ASSEMBLY = "assembly"
    CUSTOM = "custom"


@dataclass
class ObjectConfig:
    """A single object in the scene."""
    name: str
    shape: str = "Cube"
    position: List[float] = field(default_factory=lambda: [0.5, 0.0, 0.3])
    scale: List[float] = field(default_factory=lambda: [0.05, 0.05, 0.05])
    color: List[float] = field(default_factory=lambda: [0.8, 0.2, 0.2])
    mass: float = 0.05
    collision: bool = True
    usd_path: str = ""
    material: str = ""
    friction: float = 0.5
    restitution: float = 0.1
    semantic_tag: str = ""  # e.g., "grasp_target", "obstacle", "container"
    visual_only: bool = False  # if True, no collision


@dataclass
class RobotPlacement:
    """A robot in the scene."""
    model: str = "franka"
    name: str = ""
    position: List[float] = field(default_factory=lambda: [0.0, 0.0, 0.0])
    orientation: List[float] = field(default_factory=lambda: [0.0, 0.0, 0.0, 1.0])
    home_joints: Optional[List[float]] = None
    gripper_open_on_start: bool = True


@dataclass
class LightingConfig:
    """Scene lighting setup."""
    style: str = "default"  # default, bright, dim, warm, cold, colorful
    intensity: float = 1.0
    num_lights: int = 2
    shadows: bool = True


@dataclass
class CameraSetup:
    """Camera placement."""
    position: List[float] = field(default_factory=lambda: [1.2, 0.5, 1.0])
    target: List[float] = field(default_factory=lambda: [0.3, 0.0, 0.3])
    fov: float = 60.0
    resolution: Tuple[int, int] = (1280, 720)


@dataclass
class TableConfig:
    """Optional table/workbench."""
    present: bool = True
    size: Tuple[float, float] = (0.8, 1.2)
    height: float = 0.75
    position: List[float] = field(default_factory=lambda: [0.5, 0.0, 0.375])
    color: List[float] = field(default_factory=lambda: [0.4, 0.4, 0.4])


@dataclass
class DomainRandomizationConfig:
    """Domain randomization settings."""
    enabled: bool = False
    lighting_variation: float = 0.3
    texture_variation: bool = False
    object_pose_jitter: float = 0.02
    joint_noise: float = 0.02
    num_random_objects: int = 0
    random_object_types: List[str] = field(default_factory=lambda: ["Cube", "Sphere"])


@dataclass
class TaskDefinition:
    """Definition of the task to perform in the scene."""
    category: str = "reach"
    description: str = "Move end-effector to target position"
    success_criteria: str = "distance < 5cm"
    target_object: str = ""  # name of target object in scene
    max_steps: int = 500
    variations: int = 1  # number of pose variations for evaluation


@dataclass
class StructuredSceneConfig:
    """
    Complete, structured scene configuration.

    This is the core data model that bridges LLM generation → Isaac Sim execution.
    Fully serializable to/from JSON.
    """
    name: str = "autosim_scene"
    description: str = ""

    # Environment
    floor: bool = True
    table: TableConfig = field(default_factory=TableConfig)
    lighting: LightingConfig = field(default_factory=LightingConfig)
    camera: CameraSetup = field(default_factory=CameraSetup)

    # Objects
    objects: List[ObjectConfig] = field(default_factory=list)

    # Robot(s)
    robots: List[RobotPlacement] = field(default_factory=lambda: [RobotPlacement()])

    # Physics
    gravity: List[float] = field(default_factory=lambda: [0.0, 0.0, -9.81])
    substeps: int = 2
    dt: float = 1.0 / 60.0

    # Task
    task: TaskDefinition = field(default_factory=TaskDefinition)

    # Domain randomization
    domain_rand: DomainRandomizationConfig = field(default_factory=DomainRandomizationConfig)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize to dict (JSON-compatible)."""
        return json.loads(json.dumps(asdict(self), default=str))

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StructuredSceneConfig":
        """Deserialize from dict."""
        return cls(
            name=data.get("name", "scene"),
            description=data.get("description", ""),
            floor=data.get("floor", True),
            table=TableConfig(**data.get("table", {})),
            lighting=LightingConfig(**data.get("lighting", {})),
            camera=CameraSetup(**data.get("camera", {})),
            objects=[ObjectConfig(**o) for o in data.get("objects", [])],
            robots=[RobotPlacement(**r) for r in data.get("robots", [])],
            gravity=data.get("gravity", [0, 0, -9.81]),
            substeps=data.get("substeps", 2),
            dt=data.get("dt", 1.0 / 60.0),
            task=TaskDefinition(**data.get("task", {})),
            domain_rand=DomainRandomizationConfig(**data.get("domain_rand", {})),
        )


# ═══════════════════════════════════════════════════════════════════
# Pre-built scene templates
# ═══════════════════════════════════════════════════════════════════

def template_single_object_grasp() -> StructuredSceneConfig:
    """Standard single-object grasp scene: Franka + table + cube."""
    return StructuredSceneConfig(
        name="single_object_grasp",
        description="Franka robot grasping a single cube on a table",
        table=TableConfig(),
        objects=[
            ObjectConfig(
                name="grasp_target",
                shape="Cube",
                position=[0.5, 0.0, 0.4],
                scale=[0.04, 0.04, 0.04],
                color=[0.9, 0.2, 0.2],
                mass=0.05,
                semantic_tag="grasp_target",
            ),
        ],
        robots=[RobotPlacement(
            model="franka",
            position=[0.0, 0.0, 0.75],
        )],
        camera=CameraSetup(
            position=[1.5, 0.8, 1.2],
            target=[0.5, 0.0, 0.4],
        ),
        task=TaskDefinition(
            category="grasp",
            description="Grasp the red cube and lift it",
            success_criteria="object lifted > 10cm",
            target_object="grasp_target",
        ),
    )


def template_pick_and_place() -> StructuredSceneConfig:
    """Pick and place: two zones + object."""
    return StructuredSceneConfig(
        name="pick_and_place",
        description="Pick object from source zone and place in target zone",
        table=TableConfig(position=[0.5, 0.0, 0.375]),
        objects=[
            ObjectConfig(
                name="pick_object",
                shape="Cube",
                position=[0.5, 0.0, 0.4],
                scale=[0.04, 0.04, 0.04],
                color=[0.2, 0.6, 0.9],
                mass=0.05,
                semantic_tag="grasp_target",
            ),
            ObjectConfig(
                name="target_zone",
                shape="Cylinder",
                position=[0.35, -0.25, 0.02],
                scale=[0.06, 0.06, 0.02],
                color=[0.2, 0.8, 0.2],
                mass=0.0,
                collision=False,
                visual_only=True,
                semantic_tag="target_zone",
            ),
        ],
        robots=[RobotPlacement(
            model="franka",
            position=[0.0, 0.0, 0.75],
        )],
        camera=CameraSetup(
            position=[1.2, 0.6, 1.0],
            target=[0.4, -0.1, 0.3],
        ),
        task=TaskDefinition(
            category="pick_place",
            description="Pick the blue cube and place it on the green target zone",
            success_criteria="object placed within 3cm of target zone center",
            target_object="pick_object",
        ),
    )


def template_stack_blocks() -> StructuredSceneConfig:
    """Stacking: two blocks, one on top of another."""
    return StructuredSceneConfig(
        name="stack_blocks",
        description="Stack a smaller block on top of a larger block",
        table=TableConfig(position=[0.5, 0.0, 0.375]),
        objects=[
            ObjectConfig(
                name="base_block",
                shape="Cube",
                position=[0.5, 0.0, 0.4],
                scale=[0.06, 0.06, 0.06],
                color=[0.5, 0.5, 0.5],
                mass=0.1,
                semantic_tag="base",
            ),
            ObjectConfig(
                name="top_block",
                shape="Cube",
                position=[0.5, 0.0, 0.47],
                scale=[0.03, 0.03, 0.03],
                color=[0.9, 0.6, 0.2],
                mass=0.03,
                semantic_tag="grasp_target",
            ),
        ],
        robots=[RobotPlacement(
            model="franka",
            position=[0.0, 0.0, 0.75],
        )],
        task=TaskDefinition(
            category="pick_place",
            description="Pick the small orange block and place it on top of the gray base block",
            success_criteria="top block resting within 2cm of base block center",
            target_object="top_block",
        ),
    )


def template_peg_insertion() -> StructuredSceneConfig:
    """Precision peg-in-hole insertion."""
    return StructuredSceneConfig(
        name="peg_insertion",
        description="Insert a peg into a hole",
        table=TableConfig(position=[0.5, 0.0, 0.375]),
        objects=[
            ObjectConfig(
                name="peg",
                shape="Cylinder",
                position=[0.6, 0.0, 0.4],
                scale=[0.015, 0.015, 0.06],
                color=[0.7, 0.7, 0.2],
                mass=0.03,
                semantic_tag="grasp_target",
            ),
            ObjectConfig(
                name="hole_block",
                shape="Cube",
                position=[0.4, 0.0, 0.38],
                scale=[0.08, 0.08, 0.04],
                color=[0.3, 0.3, 0.3],
                mass=0.2,
                semantic_tag="fixture",
            ),
        ],
        robots=[RobotPlacement(
            model="franka",
            position=[0.0, 0.0, 0.75],
        )],
        camera=CameraSetup(
            position=[1.0, 0.5, 0.8],
            target=[0.5, 0.0, 0.3],
            fov=45.0,
        ),
        task=TaskDefinition(
            category="insertion",
            description="Grasp the yellow peg and insert it into the hole in the gray block",
            success_criteria="peg inserted to depth > 2cm",
            target_object="peg",
        ),
    )


def template_bin_picking() -> StructuredSceneConfig:
    """Bin picking: multiple objects scattered in a bin."""
    rng = __import__("numpy").random.RandomState(42)
    objects = []
    for i in range(5):
        objects.append(ObjectConfig(
            name=f"part_{i}",
            shape="Cube",
            position=[0.5 + rng.uniform(-0.1, 0.1),
                      0.0 + rng.uniform(-0.08, 0.08),
                      0.42 + i * 0.005],
            scale=[0.025, 0.025, 0.025],
            color=[rng.uniform(0.2, 0.9), rng.uniform(0.2, 0.9), rng.uniform(0.2, 0.9)],
            mass=0.02,
            semantic_tag="grasp_target",
        ))

    return StructuredSceneConfig(
        name="bin_picking",
        description="Pick one of several small parts scattered on a table",
        table=TableConfig(),
        objects=objects,
        robots=[RobotPlacement(model="franka", position=[0.0, 0.0, 0.75])],
        task=TaskDefinition(
            category="grasp",
            description="Grasp any one of the colored parts",
            success_criteria="any part lifted > 5cm",
            target_object="",
        ),
    )


def template_empty_workspace() -> StructuredSceneConfig:
    """Empty workspace with just a robot — for reach tasks."""
    return StructuredSceneConfig(
        name="empty_workspace",
        description="Franka robot in an empty workspace for reach tasks",
        table=TableConfig(),
        objects=[],
        robots=[RobotPlacement(model="franka", position=[0.0, 0.0, 0.75])],
        camera=CameraSetup(position=[1.2, 0.5, 1.0], target=[0.5, 0.0, 0.3]),
        task=TaskDefinition(
            category="reach",
            description="Move end-effector to specified 3D target",
            success_criteria="end-effector within 5cm of target",
        ),
        domain_rand=DomainRandomizationConfig(enabled=True, object_pose_jitter=0.02),
    )


TEMPLATES = {
    "single_object_grasp": template_single_object_grasp,
    "pick_and_place": template_pick_and_place,
    "stack_blocks": template_stack_blocks,
    "peg_insertion": template_peg_insertion,
    "bin_picking": template_bin_picking,
    "empty_workspace": template_empty_workspace,
}


def list_templates() -> List[str]:
    """List available scene template names."""
    return list(TEMPLATES.keys())


def get_template(name: str) -> StructuredSceneConfig:
    """Get a scene template by name."""
    fn = TEMPLATES.get(name)
    if fn is None:
        raise KeyError(f"Unknown template: {name}. Available: {list_templates()}")
    return fn()


def apply_variation(config: StructuredSceneConfig, seed: int = 0,
                    variation_scale: float = 0.1) -> StructuredSceneConfig:
    """Apply random pose variation to objects in a scene config."""
    import numpy as np
    rng = np.random.RandomState(seed)

    varied = StructuredSceneConfig.from_dict(config.to_dict())

    for obj in varied.objects:
        if obj.mass > 0:  # only movable objects
            obj.position[0] += rng.uniform(-variation_scale, variation_scale)
            obj.position[1] += rng.uniform(-variation_scale, variation_scale)
            if obj.position[2] > 0.05:  # don't move through table
                obj.position[2] += rng.uniform(-variation_scale * 0.5, variation_scale * 0.5)

    return varied
